version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://auth-mongo:27017/auth_service
    depends_on:
      - auth-mongo

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://product-mongo:27017/product_service
    depends_on:
      - product-mongo

  product-order-service:
    build: ./product-order-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGO_URI=mongodb://order-mongo:27017/order_service
    depends_on:
      - order-mongo

  gateway-service:
    build: ./gateway-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SESSION_KEY=eifjekfjhgieirj2i3u24983582375845293489yfhkjh4yhvi3y98y
      - JWT_SECRET=549d727555b4719891c1ca60a068149b15ee2433531cccd1ee5814fc0c5e8c61bb5f37f745dd6f18535fdc67632face71a32979bdfbf3a5f11ed08a6e3fb89c7
    depends_on:
      - auth-service
      - product-service
      - product-order-service

  auth-mongo:
    image: mongo
    container_name: auth-mongo
    ports:
      - "27017:27017"

  product-mongo:
    image: mongo
    container_name: product-mongo
    ports:
      - "27018:27017"

  order-mongo:
    image: mongo
    container_name: order-mongo
    ports:
      - "27019:27017"